// Dữ liệu sản phẩm (tên, giá, SKU, nhóm, ảnh).

// Mỗi sản phẩm: id, name, price (VND), sku, category ("new" / "hot" / "sale"), image (ảnh chính), image2 (ảnh hiện khi rê chuột), gallery (ảnh ở trang chi tiết).
const products = [
    { id: 1, name: "ĐẦM THUN ĐEN NHÚN EO", price: 1998000, sku: "FS2605183DMKCBK", category: "new",
      image: "image/products/1-card0.jpg", image2: "image/products/1-card1.jpg",
      gallery: ["image/products/1-g0.jpg","image/products/1-g1.jpg","image/products/1-g2.jpg","image/products/1-g3.jpg","image/products/1-g4.jpg"] },
    { id: 2, name: "QUẦN SUÔNG RỘNG NÂU BÈO CẠP", price: 1498000, sku: "FF2606082BPWOBR", category: "new",
      image: "image/products/2-card0.jpg", image2: "image/products/2-card1.jpg",
      gallery: ["image/products/2-g0.jpg","image/products/2-g1.jpg","image/products/2-g2.jpg","image/products/2-g3.jpg"] },
    { id: 3, name: "QUẦN SUÔNG DENIM NÂU", price: 1298000, sku: "FW2606222BPDEBR", category: "new",
      image: "image/products/3-card0.jpg", image2: "image/products/3-card1.jpg",
      gallery: ["image/products/3-g0.jpg","image/products/3-g1.jpg","image/products/3-g2.jpg","image/products/3-g3.jpg"] },
    { id: 4, name: "QUẦN SOOC BE KẺ CƠI TÚI", price: 1198000, sku: "FS2606127BSWOBE", category: "new",
      image: "image/products/4-card0.jpg", image2: "image/products/4-card1.jpg",
      gallery: ["image/products/4-g0.jpg","image/products/4-g1.jpg","image/products/4-g2.jpg"] },
    { id: 5, name: "QUẦN DENIM SUÔNG BE VÀNG", price: 1298000, sku: "FW2606221BPDEBE", category: "hot",
      image: "image/products/5-card0.jpg", image2: "image/products/5-card1.jpg",
      gallery: ["image/products/5-g0.jpg","image/products/5-g1.jpg","image/products/5-g2.jpg","image/products/5-g3.jpg"] },
    { id: 6, name: "QUẦN BE SUÔNG", price: 1398000, sku: "FW2606326BPKCBE", category: "hot",
      image: "image/products/6-card0.jpg", image2: "image/products/6-card1.jpg",
      gallery: ["image/products/6-g0.jpg","image/products/6-g1.jpg","image/products/6-g2.jpg","image/products/6-g3.jpg"] },
    { id: 7, name: "CV LEN NÂU A DÀI ĐÍNH LOGO", price: 1098000, sku: "FF2606266BKKFBR", category: "hot",
      image: "image/products/7-card0.jpg", image2: "image/products/7-card1.jpg",
      gallery: ["image/products/7-g0.jpg","image/products/7-g1.jpg","image/products/7-g2.jpg","image/products/7-g3.jpg"] },
    { id: 8, name: "CV KAKI NÂU SÁNG ĐAI EO", price: 1398000, sku: "FS2603048BKWOBR", category: "hot",
      image: "image/products/8-card0.jpg", image2: "image/products/8-card1.jpg",
      gallery: ["image/products/8-g0.jpg","image/products/8-g1.jpg","image/products/8-g2.jpg","image/products/8-g3.jpg"] },
    { id: 9, name: "CV ĐEN NHÚN XÒE CƠI TÚI", price: 1198000, sku: "FS2604150BKWOBK", category: "sale",
      image: "image/products/9-card0.jpg", image2: "image/products/9-card1.jpg",
      gallery: ["image/products/9-g0.jpg","image/products/9-g1.jpg","image/products/9-g2.jpg","image/products/9-g3.jpg"] },
    { id: 10, name: "CV BE GHI ĐUÔI CÁ", price: 1498000, sku: "FS2607002BKWOBE", category: "sale",
      image: "image/products/10-card0.jpg", image2: "image/products/10-card1.jpg",
      gallery: ["image/products/10-g0.jpg","image/products/10-g1.jpg","image/products/10-g2.jpg","image/products/10-g3.jpg"] },
    { id: 11, name: "CHÂN VÁY THUN ĐEN XÒE VẠT LỆCH", price: 1298000, sku: "FS2604133BKKCBK", category: "sale",
      image: "image/products/11-card0.jpg", image2: "image/products/11-card1.jpg",
      gallery: ["image/products/11-g0.jpg","image/products/11-g1.jpg","image/products/11-g2.jpg","image/products/11-g3.jpg"] },
    { id: 12, name: "CHÂN VÁY LEN BE A DÀI", price: 1298000, sku: "FW2607005BKKFBE", category: "sale",
      image: "image/products/12-card0.jpg", image2: "image/products/12-card1.jpg",
      gallery: ["image/products/12-g0.jpg","image/products/12-g1.jpg","image/products/12-g2.jpg","image/products/12-g3.jpg"] }
];
