/**
 * Danh sách sản phẩm HoangMinh - Đồ công nghệ
 * Môn học: Lập trình cơ sở với JavaScript (WEB1044)
 * Sinh viên thực hiện: Hoàng Minh
 */

const products = [
    {
        "id": 176846,
        "name": "Adobe Creative Cloud Photography Plan",
        "price": 6310000,
        "originalPrice": 7260000,
        "image": "image/product-176846.webp",
        "brand": "Adobe",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 12,
        "badge": "HOT",
        "isHot": true,
        "isNew": false,
        "sku": "23583",
        "description": "Phần mềm bản quyền Adobe Creative Cloud Photography Plan chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176852,
        "name": "Adobe Creative Cloud Pro",
        "price": 20540000,
        "originalPrice": 23620000,
        "image": "image/product-176852.webp",
        "brand": "Adobe",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 15,
        "badge": "HOT",
        "isHot": true,
        "isNew": false,
        "sku": "23584",
        "description": "Phần mềm bản quyền Adobe Creative Cloud Pro chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176856,
        "name": "Adobe Creative Cloud Pro STE – Student & Teacher Edition",
        "price": 7890000,
        "originalPrice": 9070000,
        "image": "image/product-176856.webp",
        "brand": "Adobe",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 18,
        "badge": "HOT",
        "isHot": true,
        "isNew": false,
        "sku": "23585",
        "description": "Phần mềm bản quyền Adobe Creative Cloud Pro STE – Student & Teacher Edition chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176861,
        "name": "Adobe Lightroom",
        "price": 3130000,
        "originalPrice": 3600000,
        "image": "image/product-176861.webp",
        "brand": "Adobe",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 21,
        "badge": "HOT",
        "isHot": true,
        "isNew": false,
        "sku": "23586",
        "description": "Phần mềm bản quyền Adobe Lightroom chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176828,
        "name": "BarTender 2022 Automation",
        "price": 14380000,
        "originalPrice": 16540000,
        "image": "image/product-176828.webp",
        "brand": "BarTender",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 24,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23593",
        "description": "Phần mềm bản quyền BarTender 2022 Automation chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176817,
        "name": "BarTender 2022 Enterprise",
        "price": 26200000,
        "originalPrice": 30130000,
        "image": "image/product-176817.webp",
        "brand": "BarTender",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 27,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23594",
        "description": "Phần mềm bản quyền BarTender 2022 Enterprise chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176833,
        "name": "BarTender 2022 Professional",
        "price": 7870000,
        "originalPrice": 9050000,
        "image": "image/product-176833.webp",
        "brand": "BarTender",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 30,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23595",
        "description": "Phần mềm bản quyền BarTender 2022 Professional chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176820,
        "name": "BarTender 2022 Starter",
        "price": 5240000,
        "originalPrice": 6030000,
        "image": "image/product-176820.webp",
        "brand": "BarTender",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 33,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23596",
        "description": "Phần mềm bản quyền BarTender 2022 Starter chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176838,
        "name": "Fender Studio Pro",
        "price": 5280000,
        "originalPrice": 6070000,
        "image": "image/product-176838.webp",
        "brand": "Fender",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 36,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23597",
        "description": "Phần mềm bản quyền Fender Studio Pro chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 177055,
        "name": "Microsoft 365 Family",
        "price": 3420000,
        "originalPrice": 3930000,
        "image": "image/product-177055.webp",
        "brand": "Microsoft",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 14,
        "badge": "HOT",
        "isHot": true,
        "isNew": false,
        "sku": "23601",
        "description": "Phần mềm bản quyền Microsoft 365 Family chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 177059,
        "name": "Microsoft 365 Personal",
        "price": 2390000,
        "originalPrice": 2750000,
        "image": "image/product-177059.webp",
        "brand": "Microsoft",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 17,
        "badge": "HOT",
        "isHot": true,
        "isNew": false,
        "sku": "23602",
        "description": "Phần mềm bản quyền Microsoft 365 Personal chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 177068,
        "name": "Microsoft Office Home",
        "price": 5130000,
        "originalPrice": 5900000,
        "image": "image/product-177068.webp",
        "brand": "Microsoft",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 20,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23603",
        "description": "Phần mềm bản quyền Microsoft Office Home chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 177050,
        "name": "Microsoft Office Home & Business",
        "price": 8550000,
        "originalPrice": 9830000,
        "image": "image/product-177050.webp",
        "brand": "Microsoft",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 23,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23604",
        "description": "Phần mềm bản quyền Microsoft Office Home & Business chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176842,
        "name": "TechSmith Camtasia 2024",
        "price": 7370000,
        "originalPrice": 8480000,
        "image": "image/product-176842.webp",
        "brand": "TechSmith",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 26,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23598",
        "description": "Phần mềm bản quyền TechSmith Camtasia 2024 chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 177046,
        "name": "Windows 11 Pro",
        "price": 6840000,
        "originalPrice": 7870000,
        "image": "image/product-177046.webp",
        "brand": "Microsoft",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 29,
        "badge": null,
        "isHot": false,
        "isNew": false,
        "sku": "23599",
        "description": "Phần mềm bản quyền Windows 11 Pro chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 176804,
        "name": "Windows Server 2025",
        "price": 23670000,
        "originalPrice": 27220000,
        "image": "image/product-176804.webp",
        "brand": "Microsoft",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 32,
        "badge": "MỚI",
        "isHot": false,
        "isNew": true,
        "sku": "23600",
        "description": "Phần mềm bản quyền Windows Server 2025 chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 150222,
        "name": "Đèn UV diệt khuẩn thông minh",
        "price": 800000,
        "originalPrice": 1080000,
        "image": "image/product-150222.webp",
        "brand": "Khác",
        "category": "smarthome",
        "categoryName": "Thiết bị thông minh",
        "rating": 4.8,
        "reviewsCount": 35,
        "badge": "-26%",
        "isHot": false,
        "isNew": true,
        "sku": "16852",
        "description": "Thiết bị công nghệ thông minh Đèn UV diệt khuẩn thông minh cao cấp, thiết kế hiện đại, nhiều tính năng thông minh hữu ích cho cuộc sống hàng ngày. Bảo hành 12 tháng tại HoangMinh.",
        "inStock": true
    },
    {
        "id": 185097,
        "name": "MI -Bộ Đầu Thay Thế Tâm Nước  MIJIA MEO701",
        "price": 200000,
        "originalPrice": 330000,
        "image": "image/product-185097.webp",
        "brand": "Khác",
        "category": "software",
        "categoryName": "Phần mềm & Bản quyền",
        "rating": 4.8,
        "reviewsCount": 13,
        "badge": "-39%",
        "isHot": false,
        "isNew": true,
        "sku": "17344",
        "description": "Phần mềm bản quyền MI -Bộ Đầu Thay Thế Tâm Nước  MIJIA MEO701 chính hãng 100%, bảo hành trong suốt thời gian sử dụng. Kích hoạt trực tiếp qua tài khoản chính chủ, tương thích hoàn hảo với hệ điều hành Windows và macOS.",
        "inStock": true
    },
    {
        "id": 109393,
        "name": "Bình xịt tự tạo nước khử khuẩn Dunhome Portable Disinfection Water Generator DH-003",
        "price": 1350000,
        "originalPrice": 1550000,
        "image": "image/product-109393.jpg",
        "brand": "Khác",
        "category": "smarthome",
        "categoryName": "Thiết bị thông minh",
        "rating": 4.8,
        "reviewsCount": 16,
        "badge": "MỚI",
        "isHot": false,
        "isNew": true,
        "sku": "16035",
        "description": "Thiết bị công nghệ thông minh Bình xịt tự tạo nước khử khuẩn Dunhome Portable Disinfection Water Generator DH-003 cao cấp, thiết kế hiện đại, nhiều tính năng thông minh hữu ích cho cuộc sống hàng ngày. Bảo hành 12 tháng tại HoangMinh.",
        "inStock": true
    },
    {
        "id": 39229,
        "name": "Google Nest Cam Outdoor or Indoor (Battery)",
        "price": 4500000,
        "originalPrice": 5180000,
        "image": "image/product-39229.jpg",
        "brand": "Khác",
        "category": "smarthome",
        "categoryName": "Thiết bị thông minh",
        "rating": 4.8,
        "reviewsCount": 19,
        "badge": "MỚI",
        "isHot": false,
        "isNew": true,
        "sku": "16260",
        "description": "Thiết bị công nghệ thông minh Google Nest Cam Outdoor or Indoor (Battery) cao cấp, thiết kế hiện đại, nhiều tính năng thông minh hữu ích cho cuộc sống hàng ngày. Bảo hành 12 tháng tại HoangMinh.",
        "inStock": true
    },
    {
        "id": 39228,
        "name": "Google Nest Cam Outdoor or Indoor (Battery) &#8211; 2 Pack",
        "price": 8500000,
        "originalPrice": 9780000,
        "image": "image/product-39228.jpg",
        "brand": "Khác",
        "category": "smarthome",
        "categoryName": "Thiết bị thông minh",
        "rating": 4.8,
        "reviewsCount": 22,
        "badge": "MỚI",
        "isHot": false,
        "isNew": true,
        "sku": "16259",
        "description": "Thiết bị công nghệ thông minh Google Nest Cam Outdoor or Indoor (Battery) &#8211; 2 Pack cao cấp, thiết kế hiện đại, nhiều tính năng thông minh hữu ích cho cuộc sống hàng ngày. Bảo hành 12 tháng tại HoangMinh.",
        "inStock": true
    },
    {
        "id": 39420,
        "name": "Máy massage đầu Xiaomi Mini M2",
        "price": 880000,
        "originalPrice": 0,
        "image": "image/product-39420.jpg",
        "brand": "Khác",
        "category": "smarthome",
        "categoryName": "Thiết bị thông minh",
        "rating": 4.8,
        "reviewsCount": 25,
        "badge": "MỚI",
        "isHot": false,
        "isNew": true,
        "sku": "16145",
        "description": "Thiết bị công nghệ thông minh Máy massage đầu Xiaomi Mini M2 cao cấp, thiết kế hiện đại, nhiều tính năng thông minh hữu ích cho cuộc sống hàng ngày. Bảo hành 12 tháng tại HoangMinh.",
        "inStock": true
    },
    {
        "id": 39158,
        "name": "Máy rửa rau quả Xiaomi Portable Vegetable And Fruit Cleaner (Wireless Charging)",
        "price": 750000,
        "originalPrice": 950000,
        "image": "image/product-39158.jpg",
        "brand": "Khác",
        "category": "smarthome",
        "categoryName": "Thiết bị thông minh",
        "rating": 4.8,
        "reviewsCount": 28,
        "badge": "-21%",
        "isHot": false,
        "isNew": true,
        "sku": "17359",
        "description": "Thiết bị công nghệ thông minh Máy rửa rau quả Xiaomi Portable Vegetable And Fruit Cleaner (Wireless Charging) cao cấp, thiết kế hiện đại, nhiều tính năng thông minh hữu ích cho cuộc sống hàng ngày. Bảo hành 12 tháng tại HoangMinh.",
        "inStock": true
    },
    {
        "id": 106241,
        "name": "Máy tạo Oxy Yobekan 2L Household Oxygen Concentrator KE-Y202",
        "price": 8800000,
        "originalPrice": 10120000,
        "image": "image/product-106241.jpg",
        "brand": "Khác",
        "category": "smarthome",
        "categoryName": "Thiết bị thông minh",
        "rating": 4.8,
        "reviewsCount": 31,
        "badge": "MỚI",
        "isHot": false,
        "isNew": true,
        "sku": "15580",
        "description": "Thiết bị công nghệ thông minh Máy tạo Oxy Yobekan 2L Household Oxygen Concentrator KE-Y202 cao cấp, thiết kế hiện đại, nhiều tính năng thông minh hữu ích cho cuộc sống hàng ngày. Bảo hành 12 tháng tại HoangMinh.",
        "inStock": true
    }
];
